services:
  github-runner:
    image: ghcr.io/zacholade/github-runner:latest
    restart: unless-stopped
    environment:
      - REPO_URL=https://github.com/<owner>/<repo>
      - PAT=${PAT}
      - RUNNER_NAME=${RUNNER_NAME}
      - DISABLE_AUTO_UPDATE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
