services:
  github-runner:
    image: ghcr.io/zacholade/github-runner:latest
    restart: unless-stopped
    environment:
      - REPO_URL=https://github.com/<owner>/<repo>
      - PAT=${PAT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
